micronaut:
  application:
    name: micronaut-4_5

datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

flyway:
  datasources:
    default:
      enabled: true


pulsar:
  service-url: pulsar://${PULSAR_HOST:127.0.0.1}:${PULSAR_TCP_6650:6650}
  producers:
    dummy:
      schema: just-making-sure
      tenant: presence-of-another-producer-config
      namespace: will-not-affect-grant-message-related-beans
